config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/contact', { to: 'welcome#contact', as: 'contact' }

  get '/about', { to: 'welcome#about', as: 'about' }

  get '/projects', { to: 'welcome#projects', as: 'projects' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @page_title       = 'Dead Fred Creative'
    @page_description = 'Landing/Title Page'
    @page_keywords    = 'Creative, Homepage'
  end

  def contact
    @page_title       = 'Contact'
    @page_description = 'Contact Details'
    @page_keywords    = 'Contact, Links, Information'
  end

  def about
    @page_title       = 'About'
    @page_description = 'Description of Author'
    @page_keywords    = 'Description, Author, Details'
  end

  def Projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asset_path_helper.rb
module AssetPathHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: 'Dead Fred Creative' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag("apple-icon-76x76.png") %>
    <link rel="stylesheet" href="stylesheet.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:300|Libre+Barcode+39+Text" rel="stylesheet">
    <title>Dead Fred Creative</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <div class="grid-container">
      <%= render 'shared/menu' %>
      <%= yield %>

      <footer class="main-footer">
        <%= link_to "Contact Me", contact_path, as: 'contact', class: "footer_link"%>
      </footer>
    </div>
</html>

app/views/shared/_menu.html.erb
<nav class="main-nav">
  <ul id="nav-list">
    <li class="link-item">
      <%= link_to 'Home', root_path, as: 'home', class: "nav-link" %>
    </li>
    <li class="link-item">
      <%= link_to 'About', about_path, as: 'about', class: "nav-link" %>
    </li>
    <li class="link-item">
      <%= link_to 'Projects', projects_path, as: 'projects', class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/welcome/about.html.erb
<div class="content">
  <div class="content-box">
    <div class="heading-container">
      <h1>Hi, I'm Fred Cliff.</h1>
    </div>
    <div class="blurb">
      <p>With an extensive background in the hospitality industry, I know a few things about efficiency and problem-solving. Now I’m reframing this understanding to move into the tech industry, and I study web development at Coder Academy, Brisbane to give me the skills to play the part.</p>
    </div>
  </div>
</div>

app/views/welcome/contact.html.erb
<div class="content">
  <div class="icon-container">
    <div class="icon" title="linkedin">
      <a href="https://www.linkedin.com/in/fred-cliff-4506b1147/" target="_blank">
        <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
        <metadata> Svg Vector Icons : http://www.onlinewebfonts.com/icon </metadata>
        <g>
          <g>
            <path d="M500,10C229.4,10,10,229.4,10,500c0,270.6,219.4,490,490,490c270.6,0,490-219.4,490-490C990,229.4,770.6,10,500,10z M500,913.4C271.7,913.4,86.6,728.3,86.6,500S271.7,86.6,500,86.6S913.4,271.7,913.4,500S728.3,913.4,500,913.4z"/>
            <g>
              <g>
                <path d="M255.2,744.8h91.9V377.3h-91.9V744.8z M622.7,377.3c-78.7,1.3-117.4,58.6-122.5,61.3v-61.3h-91.9v367.5h91.9V530.4c0-7.9,19.4-70.8,91.9-61.2c38.9,2.5,59.9,54,61.3,61.2v214.4l91.5,0.4V490.8C741.6,454.1,723.2,378.6,622.7,377.3z M301.1,254.8c-25.4,0-45.9,20.5-45.9,45.9s20.6,45.9,45.9,45.9s45.9-20.5,45.9-45.9S326.5,254.8,301.1,254.8z"/>
              </g>
            </g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
          <g>
          </g>
        </g>
        </svg>
      </a>
    </div>
    <div class="icon" title="Medium">
      <a href="https://medium.com/@DeadFred121" target="_blank">
        <svg enable-background="new 0 0 32 32" version="1.1" viewBox="0 0 32 32" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <g id="Style_2_copy_4">
            <g>
              <g>
                <path d="M16,0C7.163,0,0,7.163,0,16c0,8.836,7.163,16,16,16s16-7.164,16-16C32,7.163,24.837,0,16,0z" fill="#FAA916"/>
              </g>
            </g>
            <g>
              <path d="M24.959,11.076l-5.76-2.88c-0.026-0.013-0.055-0.019-0.083-0.02c-0.002,0-0.004-0.001-0.006-0.001    c-0.07,0-0.14,0.035-0.177,0.096l-3.55,5.769l3.963,6.44l5.669-9.212C25.056,11.201,25.031,11.112,24.959,11.076z"/>
              <polygon points="13.505,12.013 13.505,18.23 19.031,20.992   "/>
              <path d="M19.514,21.23l5.074,2.537c0.277,0.138,0.504-0.002,0.504-0.311v-11.29L19.514,21.23z"/>
              <path d="M12.895,11.105L7.58,8.448L7.244,8.28C7.196,8.256,7.15,8.244,7.108,8.244    c-0.059,0-0.109,0.023-0.145,0.066C6.929,8.352,6.908,8.412,6.908,8.487v12.13c0,0.206,0.151,0.451,0.336,0.543l5.222,2.611    c0.073,0.036,0.142,0.053,0.204,0.053c0.176,0,0.299-0.136,0.299-0.365V11.226C12.97,11.175,12.941,11.128,12.895,11.105z"/>
            </g>
          </g>
        </svg>
      </a>
    </div>
    <div class="icon" title="GitHub">
      <a href="https://github.com/DeadFred121" target="_blank">
        <?xml version="1.0" encoding="iso-8859-1"?>
        <!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
        <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
        <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        	 width="438.549px" height="438.549px" viewBox="0 0 438.549 438.549" style="enable-background:new 0 0 438.549 438.549;"
        	 xml:space="preserve">
        <g>
        	<path d="M409.132,114.573c-19.608-33.596-46.205-60.194-79.798-79.8C295.736,15.166,259.057,5.365,219.271,5.365
        		c-39.781,0-76.472,9.804-110.063,29.408c-33.596,19.605-60.192,46.204-79.8,79.8C9.803,148.168,0,184.854,0,224.63
        		c0,47.78,13.94,90.745,41.827,128.906c27.884,38.164,63.906,64.572,108.063,79.227c5.14,0.954,8.945,0.283,11.419-1.996
        		c2.475-2.282,3.711-5.14,3.711-8.562c0-0.571-0.049-5.708-0.144-15.417c-0.098-9.709-0.144-18.179-0.144-25.406l-6.567,1.136
        		c-4.187,0.767-9.469,1.092-15.846,1c-6.374-0.089-12.991-0.757-19.842-1.999c-6.854-1.231-13.229-4.086-19.13-8.559
        		c-5.898-4.473-10.085-10.328-12.56-17.556l-2.855-6.57c-1.903-4.374-4.899-9.233-8.992-14.559
        		c-4.093-5.331-8.232-8.945-12.419-10.848l-1.999-1.431c-1.332-0.951-2.568-2.098-3.711-3.429c-1.142-1.331-1.997-2.663-2.568-3.997
        		c-0.572-1.335-0.098-2.43,1.427-3.289c1.525-0.859,4.281-1.276,8.28-1.276l5.708,0.853c3.807,0.763,8.516,3.042,14.133,6.851
        		c5.614,3.806,10.229,8.754,13.846,14.842c4.38,7.806,9.657,13.754,15.846,17.847c6.184,4.093,12.419,6.136,18.699,6.136
        		c6.28,0,11.704-0.476,16.274-1.423c4.565-0.952,8.848-2.383,12.847-4.285c1.713-12.758,6.377-22.559,13.988-29.41
        		c-10.848-1.14-20.601-2.857-29.264-5.14c-8.658-2.286-17.605-5.996-26.835-11.14c-9.235-5.137-16.896-11.516-22.985-19.126
        		c-6.09-7.614-11.088-17.61-14.987-29.979c-3.901-12.374-5.852-26.648-5.852-42.826c0-23.035,7.52-42.637,22.557-58.817
        		c-7.044-17.318-6.379-36.732,1.997-58.24c5.52-1.715,13.706-0.428,24.554,3.853c10.85,4.283,18.794,7.952,23.84,10.994
        		c5.046,3.041,9.089,5.618,12.135,7.708c17.705-4.947,35.976-7.421,54.818-7.421s37.117,2.474,54.823,7.421l10.849-6.849
        		c7.419-4.57,16.18-8.758,26.262-12.565c10.088-3.805,17.802-4.853,23.134-3.138c8.562,21.509,9.325,40.922,2.279,58.24
        		c15.036,16.18,22.559,35.787,22.559,58.817c0,16.178-1.958,30.497-5.853,42.966c-3.9,12.471-8.941,22.457-15.125,29.979
        		c-6.191,7.521-13.901,13.85-23.131,18.986c-9.232,5.14-18.182,8.85-26.84,11.136c-8.662,2.286-18.415,4.004-29.263,5.146
        		c9.894,8.562,14.842,22.077,14.842,40.539v60.237c0,3.422,1.19,6.279,3.572,8.562c2.379,2.279,6.136,2.95,11.276,1.995
        		c44.163-14.653,80.185-41.062,108.068-79.226c27.88-38.161,41.825-81.126,41.825-128.906
        		C438.536,184.851,428.728,148.168,409.132,114.573z"/>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        <g>
        </g>
        </svg>
      </a>
    </div>
    <div class="icon" title="Email">
      <a href="mailto:deadfreddigital@gmail.com">
        <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="512px"
        	 height="512px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
        <g id="Layer_1">
        </g>
        <g id="Layer_2">
        	<path d="M456.311,97.86H55.69C33.77,97.86,16,115.629,16,137.55v236.899c0,21.92,17.77,39.69,39.69,39.69h400.621
        		c21.919,0,39.689-17.771,39.689-39.69V137.55C496,115.629,478.23,97.86,456.311,97.86z M471.815,171.038l-90.521,68.993
        		l90.521,139.379h-40.931l-85.535-111.983L256,335.527V336l-0.31-0.236L255.38,336v-0.473l-89.349-68.1L80.496,379.411h-40.93
        		l90.521-139.379l-90.521-68.993v-42.17L255.69,271.3l216.125-142.432V171.038z"/>
        </g>
        </svg>
      </a>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="content">
    <%=image_tag("DFC Logo White Background.png", id: "logo-img")%>
</div>

app/views/welcome/projects.html.erb
<div class="content">
  <div class="heading-container">
    <h1>Coming Soon!</h1>
  </div>
</div>